name: workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "README.md"
  workflow_dispatch:
    inputs:
      reason:
        description: "API triggering the workflow"
        required: false
        default: "Manual trigger"

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pandas pytest

      - name: Lint code
        run: |
          black --check .

      - name: Run unit tests
        run: |
          export PYTHONPATH="${GITHUB_WORKSPACE}:$PYTHONPATH"
          pytest tests --verbose

  run-training-pipeline:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reqs.txt

      - name: Set DAGsHub Token
        run: echo "DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Train model
        run: |
          export PYTHONPATH="${GITHUB_WORKSPACE}:$PYTHONPATH"
          python pipeline/training_pipeline.py

  # evaluate model before deploying to Cloud Run

  deploy-to-cloud-run:
    name: Continuous Deployment
    needs: run-training-pipeline
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: fraud-detection-uni

      - name: Configure Docker
        run: gcloud auth configure-docker gcr.io

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/fraud-detection-uni/fraud-detection-api:latest .
          docker push gcr.io/fraud-detection-uni/fraud-detection-api:latest

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy fraud-detection-api \
            --image gcr.io/fraud-detection-uni/fraud-detection-api:latest \
            --platform managed \
            --region asia-southeast1 \
            --allow-unauthenticated
